FROM golang:1.23-alpine
WORKDIR /app

# dependency
COPY ../shared ../shared
COPY .env /app/.env
COPY weatherService/go.mod weatherService/go.sum ./
RUN go mod download

# source code
COPY ./weatherService .
RUN go build -o weather-service .

CMD ["./weather-service"]