FROM golang:1.23-alpine
WORKDIR /app

# dependency
COPY ../shared ../shared
COPY .env /app/.env
COPY weatherAlert/go.mod weatherAlert/go.sum ./
RUN go mod download

# source code
COPY ./weatherAlert .
RUN go build -o weather-alert .
EXPOSE 8081
CMD ["./weather-alert"]